# ==========================================
# Catálogo de magias - GURPS 4e Módulo Básico (as 93 mágicas do capítulo Magia)
# ==========================================
# Descrições são resumos próprios; o texto completo está no livro, na página indicada
# (numeração impressa, igual à página do PDF "Edição de Luxo").
# Tupla: (nome, escola, classe, dificuldade, custo, tempo, duração, pré-requisitos, página, resumo)
# Dificuldade: 'D' = IQ/Difícil, 'MD' = IQ/Muito Difícil.

MAGIAS = [
    # --- Água ---
    ('Localizar Água', 'Água', 'Informação', 'D', '2', '1 s', 'Instantânea', '—', 243,
     'Indica direção, distância e tipo da fonte de água relevante mais próxima. Pede uma forquilha (-3 sem ela).'),
    ('Purificar a Água', 'Água', 'Especial', 'D', '1 a cada 4 litros', '5 a 10 s a cada 4 litros', 'Permanente',
     'Localizar Água', 243,
     'Tira todas as impurezas da água despejada através de um aro ou anel para dentro de um recipiente.'),
    ('Criar Água', 'Água', 'Comum', 'D', '2 a cada 4 litros', '1 s', 'Permanente', 'Purificar a Água', 243,
     'Faz surgir água pura num recipiente, como bola no ar ou como névoa (4 litros em névoa apagam o fogo num raio '
     'de 1 m). Não pode ser criada dentro de alguém.'),
    ('Dissipar Água', 'Água', 'Área', 'D', '3 (básico)', '1 s', 'Permanente', 'Criar Água', 243,
     'Faz a água sumir: seca coisas, salva afogados. Não serve para desidratar inimigos.'),
    ('Respirar Água', 'Água', 'Comum', 'D', '4; 2 p/ manter', '1 s', '1 min', 'Criar Ar e Dissipar Água', 243,
     'O alvo respira debaixo d\'água sem perder a respiração normal. Também é mágica de Ar.'),
    ('Moldar Água', 'Água', 'Comum', 'D', '1 a cada 80 litros; o mesmo p/ manter', '2 s', '1 min', 'Criar Água', 243,
     'Esculpe e move água, gelo ou vapor (Deslocamento 3). 80 litros fazem uma parede de 2 m × 1 m que barra fogo '
     'e Bola de Fogo.'),
    ('Nevoeiro', 'Água', 'Área', 'D', '2 (básico); metade p/ manter', '1 s', '1 min', 'Moldar Água', 243,
     'Névoa densa que bloqueia a visão. Cada metro de névoa tira 1 de dano de uma Bola de Fogo.'),
    ('Arma Congelante', 'Água', 'Comum', 'D', '3; 1 p/ manter', '3 s', '1 min', 'Criar Água', 243,
     'A arma fica gelada e causa +2 de dano quando passa da RD.'),

    # --- Ar ---
    ('Purificar o Ar', 'Ar', 'Área', 'D', '1 (básico)', '1 s', 'Instantânea (efeito permanente)', '—', 243,
     'Limpa o ar de fumaça, gases e venenos, e renova o ar viciado.'),
    ('Criar Ar', 'Ar', 'Área', 'D', '1 (básico)', '1 s', 'Brisa: 5 s; ar criado: permanente', 'Purificar o Ar', 243,
     'Cria ar onde não há: uma brisa curta ao ar livre, ar respirável no vácuo ou nos vãos dentro da pedra.'),
    ('Moldar Ar', 'Ar', 'Comum', 'D', '1 a 10; o mesmo p/ manter', '1 s', '1 min', 'Criar Ar', 244,
     'Corrente de vento de 1 m de largura, de brisa (1) a vendaval (8 ou mais). Pode derrubar e projetar pessoas.'),
    ('Eliminar Odor', 'Ar', 'Comum', 'D', '2; o mesmo p/ manter', '1 s', '1 h', 'Purificar o Ar', 244,
     'Tira o cheiro do alvo e do que ele carrega. Ninguém o rastreia pelo olfato.'),
    ('Previsão do Tempo', 'Ar', 'Informação', 'D', '2 por dia previsto (mais caro para lugares distantes)',
     '5 s por dia previsto', 'Instantânea', '4 mágicas de Ar', 244,
     'Prevê o clima de uma região pelo período escolhido, sem contar interferência mágica.'),
    ('Caminhar no Ar', 'Ar', 'Comum', 'D', '3; 2 p/ manter', '1 s', '1 min', 'Moldar Ar', 244,
     'O alvo caminha sobre o ar como se fosse chão firme. Se cair, a mágica acaba.'),
    ('Terra em Ar', 'Ar', 'Comum', 'D', '1 por 0,03 m³ (5 por 0,03 m³ de uma só vez)', '2 s', 'Permanente',
     'Criar Ar e Moldar Terra', 244,
     'Transforma terra ou pedra em ar; salva quem está soterrado. Também é mágica de Terra.'),
    ('Mau Cheiro', 'Ar', 'Área', 'D', '1 (básico)', '1 s', '5 min (menos com vento)', 'Purificar o Ar', 244,
     'Nuvem amarela de enxofre: teste de HT por minuto ou 1d de dano, além de sufocamento. Desce por ladeiras.'),
    ('Relâmpago', 'Ar', 'Projétil', 'D', 'Até a Aptidão Mágica por segundo, por até 3 s', '1 a 3 s', 'Instantânea',
     'Aptidão Mágica 1 e 6 outras mágicas de Ar', 244,
     'Raio da ponta do dedo: 1d-1 de queimadura por ponto de energia. Armadura de metal vale só RD 1 e o ferido testa '
     'HT ou fica atordoado. 1/2D 50, Máx 100, Prec 3.'),

    # --- Comunicação e Empatia ---
    ('Percepção de Inimigos', 'Comunicação e Empatia', 'Informação; Área', 'D', '1 (básico, mínimo 2)', '1 s',
     'Instantânea', '—', 245,
     'Diz se o alvo tem intenções hostis e quanto. Numa área, só revela que há alguém hostil, não quem.'),
    ('Percepção de Emoção', 'Comunicação e Empatia', 'Comum', 'D', '2', '1 s', 'Instantânea',
     'Percepção de Inimigos', 245, 'Revela as emoções do alvo e sua lealdade ao operador.'),
    ('Percepção de Veracidade', 'Comunicação e Empatia', 'Informação; Resistível (Vontade)', 'D', '2', '1 s',
     'Instantânea', 'Percepção de Emoção', 245,
     'Diz se o alvo mentiu nos últimos 5 minutos ou na última coisa que disse.'),
    ('Leitura da Mente', 'Comunicação e Empatia', 'Comum; Resistível (Vontade)', 'D', '4; 2 p/ manter', '10 s',
     '1 min', 'Percepção de Veracidade', 245,
     'Lê os pensamentos superficiais do alvo, que não percebe (a não ser numa falha crítica).'),
    ('Ocultar Pensamentos', 'Comunicação e Empatia', 'Comum', 'D', '3; 1 p/ manter', '1 s', '10 min',
     'Percepção de Veracidade', 245, 'Protege o alvo contra leitura e controle da mente.'),

    # --- Controle da Mente (não afeta quem não tem mente, como zumbis) ---
    ('Tolice', 'Controle da Mente', 'Comum; Resistível (Vontade)', 'D', '1 a 5; metade p/ manter', '1 s', '1 min',
     'IQ 12+', 245, '-1 em IQ e nas perícias de IQ (inclusive mágicas) por ponto de energia.'),
    ('Esquecimento', 'Controle da Mente', 'Comum; Resistível (Vontade ou perícia)', 'D', '3; 3 p/ manter', '10 s',
     '1 h', 'Aptidão Mágica 1 e Tolice', 245, 'O alvo esquece por um tempo um fato, uma perícia ou uma mágica.'),
    ('Torpor', 'Controle da Mente', 'Comum; Resistível (HT)', 'D', '3; 2 p/ manter', '2 s', '1 min', 'Tolice', 245,
     'O alvo parece normal, mas não percebe nada ao redor nem se lembra depois. Um ferimento quebra o efeito.'),
    ('Torpor Coletivo', 'Controle da Mente', 'Área; Resistível (HT)', 'D', '2 (básico); 1 p/ manter; raio mínimo 2 m',
     '1 s por ponto de energia', '1 min', 'Torpor e IQ 13+', 245, 'Torpor em todos de uma área.'),
    ('Sono', 'Controle da Mente', 'Comum; Resistível (HT)', 'D', '4', '3 s', 'Até acordar (cerca de 8 h)', 'Torpor',
     245, 'O alvo cai no sono. Acorda com golpe ou barulho, mas atordoado.'),
    ('Sono Coletivo', 'Controle da Mente', 'Área; Resistível (HT)', 'D', '3 (básico); raio mínimo 2 m',
     '1 s por ponto de energia', 'Até acordar', 'Sono e IQ 13+', 246, 'Sono em todos de uma área.'),
    ('Comando', 'Controle da Mente', 'Bloqueio; Resistível (Vontade)', 'D', '2', '1 s', 'Instantânea',
     'Aptidão Mágica 2 e Esquecimento', 246,
     'Uma ordem de até duas palavras que o alvo cumpre na hora, como "Solte!" ou "Olhe!".'),

    # --- Controle do Corpo ---
    ('Coceira', 'Controle do Corpo', 'Comum; Resistível (HT)', 'D', '2', '1 s', 'Até o alvo passar um turno se coçando',
     '—', 246, '-2 em DX até o alvo gastar um turno inteiro se coçando.'),
    ('Espasmo', 'Controle do Corpo', 'Comum; Resistível (HT)', 'D', '2', '1 s', 'Instantânea', 'Coceira', 246,
     'Contração num músculo: na mão, o alvo larga o que segura. Atrapalha mágicas com gestos.'),
    ('Dor', 'Controle do Corpo', 'Comum; Resistível (HT)', 'D', '2', '1 s', '1 s', 'Espasmo', 246,
     'Dor agonizante: teste de Vontade para não gritar e -3 em DX no próximo turno. Pode interromper mágicas.'),
    ('Inabilidade', 'Controle do Corpo', 'Comum; Resistível (HT)', 'D', '1 a 5; metade p/ manter', '1 s', '1 min',
     'Espasmo', 246, '-1 em DX e nas perícias de DX por ponto de energia.'),
    ('Estorvar', 'Controle do Corpo', 'Comum; Resistível (HT)', 'D', '1 a 4; o mesmo p/ manter', '1 s', '1 min',
     'Inabilidade ou Apressar', 246,
     '-1 em Deslocamento e Esquiva por ponto de energia. Também é mágica de Deslocamento.'),
    ('Pés Plantados', 'Controle do Corpo', 'Comum; Resistível (ST)', 'D', '3', '1 s', '1 min ou até se soltar',
     'Estorvar', 246, 'Os pés do alvo grudam no chão: -2 com armas corpo a corpo e Esquiva pela metade.'),
    ('Paralisar Membros', 'Controle do Corpo', 'Toque; Resistível (HT)', 'D', '3', '1 s', '1 min',
     'Aptidão Mágica 1 e 5 mágicas de Controle do Corpo, incluindo Dor', 246,
     'Ao tocar um membro, deixa-o paralisado. Armadura não protege.'),
    ('Atrofiar Membro', 'Controle do Corpo', 'Toque; Resistível (HT)', 'D', '5', '1 s', 'Permanente (até cura mágica)',
     'Aptidão Mágica 2 e Paralisar Membros', 246, 'Seca o membro tocado, que fica incapacitado, e causa 1d de dano.'),
    ('Toque Mortal', 'Controle do Corpo', 'Toque', 'D', '1 a 3', '1 s', 'Instantânea', 'Atrofiar Membro', 246,
     '1d de dano por ponto de energia ao tocar o alvo, ignorando armadura. Não afeta mortos-vivos.'),

    # --- Cura (curar a si mesmo tem penalidade igual ao dano sofrido) ---
    ('Conceder Energia', 'Cura', 'Comum', 'D', 'Qualquer (o operador passa PF ao alvo)', '1 s', 'Instantânea',
     'Aptidão Mágica 1 ou Empatia', 247,
     'Transfere fadiga: cada ponto gasto devolve 1 PF ao alvo. NH alto não reduz o custo.'),
    ('Conceder Vitalidade', 'Cura', 'Comum', 'D', 'Qualquer (1 PV por ponto)', '1 s', '1 h', 'Conceder Energia', 247,
     'Devolve PV temporários, que somem depois de 1 hora. É um quebra-galho.'),
    ('Recuperar Energia', 'Cura', 'Especial', 'D', 'Nenhum', 'Enquanto descansa', 'Contínua',
     'Aptidão Mágica 1 e Conceder Energia', 247,
     'O mago recupera fadiga mais rápido: 1 PF a cada 5 min (NH 15+) ou a cada 2 min (NH 20+). '
     'Não funciona em mana baixa.'),
    ('Despertar', 'Cura', 'Área', 'D', '1 (básico)', '1 s', 'Instantânea', 'Conceder Vitalidade', 247,
     'Acorda e tira o atordoamento. Dá bônus para quem está inconsciente despertar.'),
    ('Cura Superficial', 'Cura', 'Comum', 'D', '1 a 3 (1 PV por ponto)', '1 s', 'Instantânea', 'Conceder Vitalidade',
     247, 'Cura até 3 PV. Repetir no mesmo alvo no mesmo dia dá -3 cumulativo.'),
    ('Cura Profunda', 'Cura', 'Comum', 'MD', '1 a 4 (2 PV por ponto)', '1 s', 'Instantânea',
     'Aptidão Mágica 1 e Cura Superficial', 247,
     'Cura até 8 PV. Mesmas penalidades de repetição da Cura Superficial, contadas à parte.'),
    ('Cura Superior', 'Cura', 'Comum', 'MD', '20', '1 s', 'Instantânea', 'Aptidão Mágica 3 e Cura Profunda', 247,
     'Cura todos os PV perdidos. Uma vez por dia por paciente.'),

    # --- Deslocamento ---
    ('Apressar', 'Deslocamento', 'Comum', 'D', '2 por ponto (até +3); 1 por ponto p/ manter', '2 s', '1 min', '—',
     247, '+1 a +3 em Deslocamento e Esquiva.'),
    ('Acelerar', 'Deslocamento', 'Comum', 'MD', '5', '3 s', '10 s', 'Aptidão Mágica 1, IQ 12+ e Apressar', 248,
     'O alvo age com o dobro de velocidade (Padrão de Tempo Alterado). No fim perde 5 PF, se não for o operador.'),
    ('Aporte', 'Deslocamento', 'Comum; Resistível (Vontade)', 'D',
     '1 (até 0,5 kg) a 4 (até 100 kg), +4 a cada 50 kg; o mesmo p/ manter', '1 s', '1 min', 'Aptidão Mágica 1', 248,
     'Telecinese: levita objetos com Deslocamento 1, sem força para ferir.'),
    ('Chave-Mestra', 'Deslocamento', 'Comum; Resistível (Tranca Mágica)', 'D', '3', '10 s',
     'Até a fechadura ser fechada de novo', 'Aptidão Mágica 2 e Aporte', 248, 'Abre fechaduras com magia.'),
    ('Desviar Projétil', 'Deslocamento', 'Bloqueio', 'D', '1', '1 s', 'Instantânea', 'Aporte', 248,
     'Desvia um projétil, inclusive mágico, que vai acertar o alvo. Conta como Aparar.'),

    # --- Fogo ---
    ('Atear Fogo', 'Fogo', 'Comum', 'D', '1 a 4 conforme o calor; o mesmo p/ manter', '1 s', '1 s', '—', 248,
     'Ponto de calor que acende o que é inflamável, de fósforo (1) a magnésio (4). Não incendeia seres vivos.'),
    ('Criar Fogo', 'Fogo', 'Área', 'D', '2 (básico); metade p/ manter', '1 s', '1 min', 'Atear Fogo', 248,
     'Fogo real sem combustível. No ar, vira uma bola de chamas que cai.'),
    ('Moldar Fogo', 'Fogo', 'Área', 'D', '2 (básico); metade p/ manter', '1 s', '1 min', 'Atear Fogo', 248,
     'Dá forma às chamas e move-as a até 5 m/s (exige concentração). Espalhar o fogo reduz o dano.'),
    ('Desviar Energia', 'Fogo', 'Bloqueio', 'D', '1', '1 s', 'Instantânea', 'Aptidão Mágica 1 e Moldar Fogo', 248,
     'Desvia um ataque de energia, como Bola de Fogo ou Relâmpago. Conta como Aparar.'),
    ('Extinguir Fogo', 'Fogo', 'Área', 'D', '3 (básico)', '1 s', 'Permanente', 'Atear Fogo', 249,
     'Apaga fogo comum ou mágico na área (não lava nem metal derretido).'),
    ('Calor', 'Fogo', 'Comum', 'D', '1 (objeto do tamanho de um punho) ou 2 por 0,75 m³; o mesmo p/ manter', '1 min',
     '1 min', 'Criar Fogo e Moldar Fogo', 249, 'Esquenta um objeto 10 °C por minuto, até 1.500 °C.'),
    ('Frio', 'Fogo', 'Comum', 'D', 'Igual a Calor', '1 min', '1 min', 'Calor', 249,
     'Esfria um objeto 10 °C por minuto.'),
    ('Imunidade ao Frio', 'Fogo', 'Comum', 'D', '2; 1 p/ manter (dobra em frio extremo)', '1 s', '1 min', 'Calor',
     249, 'O alvo e o que ele carrega ficam imunes a frio e congelamento.'),
    ('Imunidade ao Fogo', 'Fogo', 'Comum', 'D', '2; 1 p/ manter (mais caro em calor extremo)', '1 s', '1 min',
     'Extinguir Fogo e Frio', 249,
     'Imunidade a calor e fogo, inclusive de mágicas de combate. Não protege de eletricidade.'),
    ('Bola de Fogo', 'Fogo', 'Projétil', 'D', 'Até a Aptidão Mágica por segundo, por até 3 s', '1 a 3 s',
     'Instantânea', 'Aptidão Mágica 1, Criar Fogo e Moldar Fogo', 249,
     '1d de queimadura por ponto de energia e incendeia o que for inflamável. 1/2D 25, Máx 50, Prec 1.'),
    ('Bola de Fogo Explosiva', 'Fogo', 'Projétil', 'D', 'Até o dobro da Aptidão Mágica por segundo, por até 3 s',
     '1 a 3 s', 'Instantânea', 'Bola de Fogo', 249,
     'Explode: 1d a cada 2 pontos de energia no alvo e a até 1 m dele; mais longe, dano dividido por 3 × a distância. '
     'Mirar no chão ou numa parede dá +4.'),

    # --- Luz e Trevas ---
    ('Luz', 'Luz e Trevas', 'Comum', 'D', '1; 1 p/ manter', '1 s', '1 min', '—', 249,
     'Luz fraca como a de uma vela. Move-se a 5 m/s com concentração.'),
    ('Luz Contínua', 'Luz e Trevas', 'Comum', 'D', '2 (fraca), 4 (como fogo) ou 6 (ofuscante)', '1 s', '2d dias',
     'Luz', 249, 'Faz um objeto pequeno brilhar por dias.'),
    ('Trevas', 'Luz e Trevas', 'Área', 'D', '2 (básico); 1 p/ manter', '1 s', '1 min', 'Luz Contínua', 249,
     'Escuridão total. Quem está dentro vê o lado de fora; de fora não se vê nada lá dentro.'),
    ('Nublar', 'Luz e Trevas', 'Comum', 'D', '1 a 5; o mesmo p/ manter', '2 s', '1 min', 'Trevas', 250,
     '-1 por ponto de energia (máximo -5) em ataques contra o alvo.'),

    # --- Necromancia ---
    ('Visão da Morte', 'Necromancia', 'Comum', 'D', '2', '3 s', '1 s', 'Aptidão Mágica 1', 250,
     'O alvo tem uma visão da própria morte e fica atordoado até passar num teste de IQ.'),
    ('Percepção de Espíritos', 'Necromancia', 'Informação; Área', 'D', '1/2 (básico)', '1 s', 'Instantânea',
     'Visão da Morte', 250, 'Detecta fantasmas, espíritos e mortos-vivos na área.'),
    ('Convocar Espíritos', 'Necromancia', 'Informação; Resistível (Vontade do espírito)', 'D', '20; metade para repetir',
     '5 min', '1 min por pergunta', 'Aptidão Mágica 2 e Visão da Morte', 250,
     'Chama o espírito de um morto para responder perguntas. Se falhar, não pode chamá-lo de novo por um ano.'),
    ('Zumbi', 'Necromancia', 'Comum', 'D', '8 (× 1+MT para criaturas maiores)', '1 min', 'Até ser destruído',
     'Convocar Espíritos e Conceder Vitalidade', 250,
     'Ergue um cadáver como servo morto-vivo (zumbi, esqueleto ou múmia), sem mente nem memórias.'),
    ('Espantar Zumbi', 'Necromancia', 'Área', 'D', '2 (básico)', '4 s', 'Um dia (para os que fogem)', 'Zumbi', 250,
     '1d de dano, ignorando RD, nos mortos-vivos erguidos por Zumbi. Com 1 no dado, cada um foge do operador.'),
    ('Convocar Demônio', 'Necromancia', 'Especial', 'D', '1 a cada 10 pontos do demônio (mínimo 20)', '5 min',
     'Até cumprir a tarefa ou 1 h', 'Aptidão Mágica 1 e 1 mágica de 10 escolas', 250,
     'Chama um demônio que cumpre uma ordem ao pé da letra. Se não for controlado, ataca.'),
    ('Expulsar', 'Necromancia', 'Especial; Resistível (Vontade)', 'D', '1 a cada 10 pontos do alvo', '5 s',
     'Instantânea', 'Aptidão Mágica 1 e 1 mágica de 10 escolas', 251,
     'Manda um ser de outro plano de volta para casa, de onde não sai por um mês.'),

    # --- Portal ---
    ('Convocação Planar', 'Portal', 'Especial', 'D', '1 a cada 10 pontos da criatura (mínimo 20)', '5 min',
     'Até cumprir a tarefa ou 1 h', 'Aptidão Mágica 1 e 1 mágica de 10 escolas', 251,
     'Chama uma criatura de outro plano. É preciso vencer a Vontade dela para dar uma ordem.'),
    ('Viagem Planar', 'Portal', 'Especial', 'MD', '20', '5 s', 'Permanente', 'Convocação Planar para o mesmo plano',
     251, 'Leva o operador, com carga até Pesada, a outro plano. Só ida.'),

    # --- Proteção e Aviso ---
    ('Escudo', 'Proteção e Aviso', 'Comum', 'D', '2 × o Bônus de Defesa (máx. 4); metade p/ manter', '1 s', '1 min',
     'Aptidão Mágica 2', 251, 'Escudo de energia que dá Bônus de Defesa, somado ao de um escudo de verdade.'),
    ('Armadura', 'Proteção e Aviso', 'Comum', 'D', '2 × a RD (máx. 5); metade p/ manter', '1 s', '1 min',
     'Aptidão Mágica 2 e Escudo', 251, 'Dá RD ao alvo vivo, somada à da armadura.'),
    ('Tranca Mágica', 'Proteção e Aviso', 'Comum; Resistível (Chave-Mestra)', 'D', '3; 2 p/ manter', '4 s', '6 h',
     'Aptidão Mágica 1', 252, 'Tranca uma porta até a mágica ser desfeita ou a porta destruída.'),

    # --- Reconhecimento ---
    ('Detecção de Magia', 'Reconhecimento', 'Comum', 'D', '2', '5 s', 'Instantânea', 'Aptidão Mágica 1', 252,
     'Diz se um objeto é encantado e, num segundo teste, se a magia é temporária ou permanente.'),
    ('Aura', 'Reconhecimento', 'Informação', 'D', '3', '1 s', 'Instantânea', 'Detecção de Magia', 252,
     'Mostra a aura do alvo: personalidade, se é mago, se está possuído ou controlado. Mortos-vivos têm aura fraca; '
     'ilusões não têm aura.'),
    ('Localizador', 'Reconhecimento', 'Informação', 'D', '3 (uma tentativa por semana)', '1 s', 'Instantânea',
     'Aptidão Mágica 1, IQ 12+ e 2 mágicas de Localizar', 252,
     'Dá o paradeiro de uma pessoa ou objeto conhecido. Sem algo ligado ao alvo, -5.'),
    ('Rastrear', 'Reconhecimento', 'Comum', 'D', '3; 1 p/ manter', '1 min', '1 h', 'Localizador', 252,
     'Enquanto a mágica dura, o operador sabe onde o alvo está.'),
    ('Identificar Mágica', 'Reconhecimento', 'Informação', 'D', '2', '1 s', 'Instantânea', 'Detecção de Magia', 252,
     'Revela as mágicas lançadas pelo alvo ou contra ele nos últimos 5 segundos.'),
    ('Analisar Mágica', 'Reconhecimento', 'Informação; Resistível (mágicas de ocultação)', 'D', '8', '1 h',
     'Instantânea', 'Identificar Mágica', 252, 'Diz exatamente quais mágicas estão afetando o alvo, uma por vez.'),

    # --- Terra ---
    ('Localizar Terra', 'Terra', 'Informação', 'D', '3', '10 s', 'Instantânea', '—', 252,
     'Direção e distância da fonte de terra, rocha ou metal mais próxima.'),
    ('Moldar Terra', 'Terra', 'Comum', 'D', '1 por 0,75 m³ (mínimo 2); metade p/ manter', '1 s', '1 min',
     'Localizar Terra', 252,
     'Move e molda a terra (Deslocamento 2): muros, buracos, enterrar quem não sair do lugar.'),
    ('Terra para Pedra', 'Terra', 'Comum', 'D', '3 por 0,75 m³ (mínimo 3)', '1 s', 'Permanente',
     'Aptidão Mágica 1 e Moldar Terra', 253, 'Transforma terra ou argila em rocha.'),
    ('Criar Terra', 'Terra', 'Comum', 'D', '2 por 0,75 m³ (mínimo 2), ou 1 para firmar lama', '1 s', 'Permanente',
     'Terra para Pedra', 253, 'Cria terra boa em contato com o chão, ou transforma lama em terra firme.'),
    ('Carne para Pedra', 'Terra', 'Comum; Resistível (HT)', 'D', '10', '2 s', 'Permanente (até Pedra para Carne)',
     'Terra para Pedra', 253, 'Petrifica um ser vivo inteiro, junto com o equipamento.'),
    ('Pedra para Terra', 'Terra', 'Comum', 'D', '6 por 0,75 m³ (mínimo 6)', '1 s', 'Permanente',
     'Terra para Pedra ou 4 mágicas de Terra', 253, 'Transforma uma pedra ou bloco inteiro em terra.'),
    ('Pedra para Carne', 'Terra', 'Comum', 'D', '10', '5 s', 'Permanente',
     'Aptidão Mágica 2, Carne para Pedra e Pedra para Terra', 253,
     'Desfaz a petrificação; a vítima volta atordoada.'),
    ('Soterramento', 'Terra', 'Comum; Resistível (HT)', 'D', '10 (6 para desfazer)', '1 s',
     'Permanente (até ser desfeita)', 'Aptidão Mágica 2 e 5 mágicas de Terra', 253,
     'A terra engole o alvo e o prende inconsciente numa câmara 150 m abaixo do chão.'),

    # --- Metamágica ---
    ('Contramágica', 'Metamágica', 'Comum; Resistível (a mágica alvo)', 'D', 'Metade do custo da mágica cancelada',
     '5 s', 'Instantânea', 'Aptidão Mágica 1', 253,
     'Cancela uma mágica ativa que o operador conheça. Não desfaz efeitos permanentes.'),
    ('Anular Mágica', 'Metamágica', 'Área; Resistível (a mágica alvo)', 'D', '3 (básico)',
     '1 s por ponto de energia', 'Permanente', 'Contramágica e 12 outras mágicas', 253,
     'Anula todas as mágicas da área, sem escolher.'),
]
